name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        go-version: ['1.21']
        platform: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Build
        run: go build -o motivate-${{ matrix.platform }} .
      
      - name: Upload macOS binary
        if: matrix.platform == 'macos-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            motivate-macos-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload Linux binary
        if: matrix.platform == 'ubuntu-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            motivate-ubuntu-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload Windows binary
        if: matrix.platform == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            motivate-windows-latest.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  homebrew:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Create Homebrew Pull Request
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          formula: motivational-quotes
          tap: ${{ github.repository_owner }}/homebrew-tap
          tag: ${{ github.ref_name }}
          force: true
